version: "2.2"

services:
  acars_kibana:
    container_name: acars_kibana
    restart: unless-stopped
    image: kibana:8.5.3
    environment:
      SERVER_NAME: "acars_kibana"
      ELASTICSEARCH_HOSTS: "http://172.18.0.2:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
      ELASTICSEARCH_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    volumes:
      - ${KIBANA_DATA_PATH}:/usr/share/kibana/data:Z
    ports:
      - "${KIBANA_PORT}:5601"
